"""kb_engine.serve — QueryParams envelope, search/get with provenance,
typed abstention, opaque cursor pagination (plan §6.5)."""

from kb_engine.serve.params import (
    OPS,
    QueryFilter,
    QueryParams,
    QueryParamsError,
    SortKey,
    parse_filters,
    parse_sort,
)
from kb_engine.serve.serve import (
    DEFAULT_MARGIN_RATIO,
    DEFAULT_MAX_TOP_K,
    DEFAULT_MIN_COVERAGE,
    GetResult,
    ModeError,
    RecordStoreRequired,
    ServeHit,
    SearchResult,
    ServeConfig,
    StaleCursorError,
    ServeError,
    content_tokens,
    coverage_ratio,
    get,
    relative_margin,
    serve,
)

__all__ = [
    "DEFAULT_MARGIN_RATIO",
    "DEFAULT_MAX_TOP_K",
    "DEFAULT_MIN_COVERAGE",
    "OPS",
    "GetResult",
    "ModeError",
    "QueryFilter",
    "QueryParams",
    "QueryParamsError",
    "RecordStoreRequired",
    "ServeHit",
    "SearchResult",
    "ServeConfig",
    "ServeError",
    "SortKey",
    "StaleCursorError",
    "content_tokens",
    "coverage_ratio",
    "get",
    "parse_filters",
    "parse_sort",
    "relative_margin",
    "serve",
]
